#!/bin/sh

# Install Big Blue Button

BBBHOST=
TLSHOST=`hostname`
PPA=

while getopts "n:p:s:h" flag
do
	case $flag in
	n)
		BBBHOST=$OPTARG;;
	p)
		PPA=$OPTARG;;
	n)
		TLSHOST=$OPTARG;;
	h)
		usage;;
	esac
done

usage() {
	echo "bbb-install [-p ffmpeg-ppa-url] [-n hostname-or-ip] [-s tls_hostname]"
	exit 1
}

# Do not run as root.  Create a user ('ubuntu'?) and add to the sudo group

if [ `id -u` -eq 0 ]
then
	echo "Do not run as root.  Create a user ('ubuntu'?) and add to the sudo group"
	echo "e.g. adduser ubuntu; gpasswd --add ubuntu sudo; su ubuntu; cd"
	exit 1
fi

# Check we're 64 bit
if [ `uname -m` != 'x86_64' ]
then
	echo "Requires 64 bit distro"
	exit 1
fi

# Check we're installing on Ubuntu trusty 14.04
if [ `lsb_release -si` != 'Ubuntu' ]
then
	echo "Requires Ubuntu"
	exit 1
fi
if [ `lsb_release -sc` != 'trusty' ]
then
	echo "Requires Ubuntu trusty"
	exit 1
fi
if [ `lsb_release -sr` != '14.04' ]
then
	echo "Requires Ubuntu trusty 14.04.x"
	exit 1
fi

# Should check other prerequisites: 4GB RAM (8GB preferred), quad CPU cores, 2.6 GHz clock minimum, 500 GB disk space, etc.

# Make sure the FFMPEG install script is present and executable

if [ ! -x ./install-ffmpeg.sh ]
then
	echo "FFMPEG install script is missing"
	exit 1
fi

# Make sure the SSL certificate is present

if [ ! -f ./ssl.key ]
then
	echo "SSL key is missing"
	exit 1
fi

if [ ! -f ./ssl.crt ]
then
	echo "SSL certificate is missing"
	exit 1
fi

if [ ! -f ./ssl.ca ]
then
	echo "SSL certificate authority is missing (can be empty)"
	exit 1
fi

#apt-get install lsof
#apt-get install iptables

# Make sure locale is set to en_US.UTF-8

sudo apt-get -f install language-pack-en
sudo locale-gen en_US.UTF-8
sudo update-locale LANG=en_US.UTF-8 LC_MESSAGES=POSIX

# Make sure we have multiverse

grep -q -e '^deb (.*?) multiverse' /etc/apt/sources.list
if [ $? -ne 0 ]
then
	sudo echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse" | sudo tee -a /etc/apt/sources.list
fi
sudo apt-get update
sudo apt-get dist-upgrade

# Install PPA repository, if specified

if [ "${PPA}x" != "x" ]
then
	sudo add-apt-repository -y ppa:${PPA}
	sudo apt-get update
fi

# Install LibreOffice repository

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:libreoffice/libreoffice-4-4
sudo add-apt-repository -y ppa:ondrej/php

# Install BBB key and add repository

wget http://ubuntu.bigbluebutton.org/bigbluebutton.asc -O- | sudo apt-key add -
sudo echo "deb http://ubuntu.bigbluebutton.org/trusty-1-0/ bigbluebutton-trusty main" | sudo tee /etc/apt/sources.list.d/bigbluebutton.list
sudo apt-get update

# Install FFMPEG
if [ "${PPA}x" != "x" ]
then
	sudo apt-get install ffmpeg
else
	sudo ./install-ffmpeg.sh
fi

ffmpeg -version
if [ $? -ne 0 ]
then
	echo "FFMPEG failed to install"
	exit 1
fi

# Install BBB

sudo apt-get install bigbluebutton

# Install optional modules

mods=bbb-demo bbb-check
# sudo apt-get install $mods

# Configure SSL

if [ ! -d /etc/nginx/ssl ]
then
	sudo mkdir -p /etc/nginx/ssl
fi

sudo cp -p ./ssl.key /etc/nginx/ssl/${TLSHOST}.key
sudo chmod 600 /etc/nginx/ssl/${TLSHOST}.key

sudo cat ./ssl.crt >/etc/nginx/ssl/${TLSHOST}.crt
sudo cat ./ssl.ca >>/etc/nginx/ssl/${TLSHOST}.crt

sudo openssl dhparam -out /etc/nginx/ssl/dhp-2048.pem 2048

cat << EOF > ssl-snippet
  listen 443 ssl;
  ssl_certificate /etc/nginx/ssl/${TLSHOST}.crt;
  ssl_certificate_key /etc/nginx/ssl/${TLSHOST}.key;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS:!AES256";
  ssl_prefer_server_ciphers on;
  ssl_dhparam /etc/nginx/ssl/dhp-2048.pem;
EOF
sudo sed -e '/listen\s+80/r ssl-snippet' -i /etc/nginx/sites-available/bigbluebutton
sudo sed -e 's/<param name="ws-binding" value="[^"]*">/<param name="wss-binding" value=":7443">/g' -i /opt/freeswitch/conf/sip_profiles/external.xml
sudo sed -e 's|proxypass .*;$|proxypass https://127.0.0.1:7443;|g' -i /etc/bigbluebutton/nginx/sip.nginx

for f in  /var/www/bigbluebutton/client/lib/bbb_webrtc_bridge_sip.js \
	/var/www/bigbluebutton/check/resources/lib/bbb_webrtc_bridge_sip.js
do
	if [ -f ${f} ]
	then
		sudo sed -e 's|ws://|wss://|g' -i ${f}
	fi
done

for f in /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties \
	/var/www/bigbluebutton/client/conf/config.xml
do
	if [ -f ${f} ]
	then
		sudo sed -e 's|http://|https://|g' -i ${f}
	fi
done

# Open the firewall (should do this permanently)

sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 1935 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 9123 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 5066 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 7443 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 16384:32768 -j ACCEPT

# Turn on WebRTC and restart

sudo bbb-conf --enablewebrtc
if [ "${BBBHOST}x" != "x" ]
then
	sudo bbb-conf --setip ${BBBHOST}
fi
sudo bbb-conf --clean
sudo bbb-conf --check

